import pandas as pd
import numpy as np

civic = ['arrestNorm',
              'censorNorm',
              'electionactivityNorm',
              'electionirregularitiesNorm',
              'cooperateNorm',
              'coupNorm',
              'defamationcaseNorm',
              'disasterNorm',
              'legalactionNorm',
              'legalchangeNorm',
              'martiallawNorm',
              'mobilizesecurityNorm',
              'corruptionNorm',
              'activismNorm',
              'protestNorm',
              'purgeNorm',
              'raidNorm',
              'threatenNorm',
              'violencelethalNorm',
              'violencenonlethalNorm'
            ]

rai = [
    'arms_transfer_security_aid_assistanceNorm',
    'bribery_economic_corruptionNorm',
    'diaspora_activationNorm',
    'diplomatic_mediationNorm',
    'diplomatic_recognitionNorm',
    'diplomatic_sanctionNorm',
    'diplomatic_statementNorm',
    'diplomatic_visitNorm',
    "economic_aid_assistanceNorm", 
    "intelligence_counterintelligenceNorm",
    "investmentNorm", 
    "joint_security_force_exerciseNorm", 
    "media_campaign_interventionNorm",
    "political_process_policy_interventionNorm", 
    "professional_cultural_exchangeNorm",
    "security_cooperationNorm", 
    "security_force_facility_presenceNorm",
    "surveillanceNorm", 
    "tech_transfer_investmentNorm", 
    "trade_agreement_exchangeNorm",
    "trade_financial_sanctionNorm", 
    "transnational_organization_crimeNorm",
    'backlash_sumNorm',
    'diplomacy_sumNorm',
    'domestic_interference_sumNorm',
    'economic_power_sumNorm',
    'hard_power_sumNorm',
    'soft_power_sumNorm'
]

