import pandas as pd
import numpy as np

civic = ['arrestNorm',
              'censorNorm',
              'electionactivityNorm',
              'electionirregularitiesNorm',
              'cooperateNorm',
              'coupNorm',
              'defamationcaseNorm',
              'disasterNorm',
              'legalactionNorm',
              'legalchangeNorm',
              'martiallawNorm',
              'mobilizesecurityNorm',
              'corruptionNorm',
              'activismNorm',
              'protestNorm',
              'purgeNorm',
              'raidNorm',
              'threatenNorm',
              'violencelethalNorm',
              'violencenonlethalNorm'
            ]

rai = ['arms_transfer_security_aid_assistanceNorm', 
       'bribery_economic_corruptionNorm', 
       'cyber_attackNorm', 
       'diplomatic_actionNorm', 
       'diplomatic_mediationNorm', 
       'diplomatic_meetingNorm',
       'diplomatic_statementNorm', 
       'diplomatic_tiesNorm', 
       'foreign_aid_assistanceNorm', 
       'foreign_investmentNorm', 
       'intelligence_counterintelligenceNorm', 
       'joint_security_force_exerciseNorm',
       'media_campaign_interventionNorm', 
       'military_activityNorm', 
       'political_process_policy_interventionNorm', 
       'security_engagementNorm', 
       'social_academic_cultural_activityNorm',
       'tech_transfer_investmentNorm', 
       'trade_agreement_exchangeNorm', 
       'trade_financial_sanctionNorm', 
       'transnational_organization_crimeNorm',
       'backlash_sumNorm',
       'diplomacy_sumNorm',
       'domestic_interference_sumNorm',
       'economic_power_sumNorm',
       'hard_power_sumNorm',
       'soft_power_sumNorm'
]

